package com.github.moribund.entity;

import com.esotericsoftware.kryonet.Connection;

/**
 * The {@code PlayableCharacter} interface is a template
 * for a character that can be interacted with by keys. All
 * playable characters are assumed as visible and movable.
 */
public interface PlayableCharacter {

    float getRotation();

    void setRotation(float angle);

    float getX();

    void setX(float x);

    float getY();

    void setY(float y);

    /**
     * Gets the player's unique ID generated by the connection.
     * @return The Player's unique ID.
     */
    int getPlayerId();

    /**
     * Gets the connection of the server between the client.
     * @return The connection of the server between the client.
     */
    Connection getConnection();
}