package com.github.moribund.entity;

import com.esotericsoftware.kryonet.Connection;

/**
 * The {@code PlayableCharacter} interface is a template
 * for a character that can be interacted with by keys. All
 * playable characters are assumed as visible and movable.
 */
public interface PlayableCharacter {
    /**
     * Gets the x-coordinate of the {@code Movable}.
     * @return The x-coordinate.
     */
    float getX();

    /**
     * Gets the y-coordinate of the {@code Movable}.
     * @return The y-coordinate.
     */
    float getY();

    /**
     * Sets the x-coordinate of the {@code Movable}.
     */
    void setX(float x);

    /**
     * Sets the y-coordinate of the {@code Movable}.
     */
    void setY(float y);

    /**
     * Sets the rotational angle of the {@code Movable}.
     */
    void setRotation(float angle);

    /**
     * Gets the rotational angle of the {@code Movable}.
     * @return The rotational angle.
     */
    float getRotation();

    int getGameId();
    /**
     * Gets the player's unique ID generated by the connection.
     * @return The Player's unique ID.
     */
    int getPlayerId();

    /**
     * Gets the connection of the server between the client.
     * @return The connection of the server between the client.
     */
    Connection getConnection();
}