package com.github.moribund.entity;

import com.esotericsoftware.kryonet.Connection;

/**
 * The {@code PlayableCharacter} interface is a template
 * for a character that can be interacted with by keys. All
 * playable characters are assumed as visible and movable.
 */
public interface PlayableCharacter {
    /**
     * Gets the current {@link Tile} the player is on.
     * @return The {@link Tile} the player is on.
     */
    Tile getCurrentTile();

    /**
     * Sets a new {@link Tile} for the player to now currently be on.
     * @param tile The new {@link Tile} for the player.
     */
    void setTile(Tile tile);

    /**
     * Gets the player's unique ID generated by the connection.
     * @return The Player's unique ID.
     */
    int getPlayerId();

    /**
     * Gets the connection of the server between the client.
     * @return The connection of the server between the client.
     */
    Connection getConnection();
}
